/* Arduino DRO Adaptor
This code reads 21-bit data frames from a DRO scale using a clock and data line generated by the scale.
It uses interrupts to capture the clock signal and read the corresponding data bits, ensuring accurate timing and synchronization.
The received data is stored to be re-emitted to a TouchDRO adaptor using a clock generated by the adaptor itself,
allowing the TouchDRO to receive the data as if it were directly connected to a scale that requires an external clock.   

*/
#include <Arduino.h>

// Pin definitions
#define INPUT_CLOCK_PIN 1  // D1 This is the input for the clock signal generated by the DRO scale.
#define INPUT_DATA_PIN 2   // D2 This is the input for the data signal generated by the DRO scale.
#define OUTPUT_CLOCK_PIN 3  // D3 This is the input for the clock signal generated by the TouchDRO adaptor.  
#define OUTPUT_DATA_PIN 4   // D4 This is the output for the data signal that will be sent to the TouchDRO adaptor.

#define MAX_BITS 21
#define MAX_CLOCK_INTERVAL 150  // Maximum expected interval between bit time clock pulses in microseconds


// Volatile variables for interrupt handling
volatile uint32_t receivedData = 0;
volatile int bitCount = 0;
volatile bool dataReady = false;
volatile bool firstClockFound = false;  // first clock pulse correctly detected

volatile uint32_t lastClockTime = 0;  
volatile uint32_t clockInterval = 0;

// Interrupt service routine for the inputclock signal
void onInputClock() {

  // Get the current time in microseconds
  uint32_t currentTime = micros();
  // Calculate the interval between clock pulses
  clockInterval = currentTime - lastClockTime;  
  lastClockTime = currentTime;  // Update last clock time
  
  if (bitCount == 0) { // Only check for the first clock pulse when we are expecting the start of a new data frame
    firstClockFound = clockInterval > MAX_CLOCK_INTERVAL;  // Check if the interval indicates the first clock pulse of a new data frame
  }
  
  if (!firstClockFound) {
    // 
    return;
  }

  // Read the data bit
  int bit = digitalRead(INPUT_DATA_PIN);
  
  // Shift in the bit (the scale does not send the bits MSB first, but we are not interpreting the data as a number, just re-emitting it, so we can shift in the bits as they come)
  receivedData = (receivedData << 1) | bit;
  
  // Increment bit count
  bitCount++;
  
  // Check if we have received all 21 bits
  if (bitCount >= 21) {
    dataReady = true;
    firstClockFound = false;  // Reset for the next data frame
    bitCount = 0;  // Reset bit count for the next data frame
  }
  }


void setup() {
  // Initialize serial for output
  Serial.begin(9600);
  
  // Set pin modes
  pinMode(INPUT_CLOCK_PIN, INPUT);
  pinMode(INPUT_DATA_PIN, INPUT);
  
  // Attach interrupt to clock pin (falling edge)
  attachInterrupt(digitalPinToInterrupt(INPUT_CLOCK_PIN), onInputClock, FALLING);
  
  Serial.println("DRO Adaptor initialized. Waiting for data...");
}

void loop() {
  // Check if data is ready
  if (dataReady) {
    // Disable interrupts temporarily to safely read volatile variables
    noInterrupts();
    uint32_t data = receivedData;
    int count = bitCount;
    dataReady = false;
    bitCount = 0;
    receivedData = 0;
    interrupts();
    
    // Process the received data (mask to 21 bits)
    uint32_t value = data & 0x1FFFFF;  // 21 bits mask
    
    // Output the value
    Serial.print("Received 21-bit value: ");
    Serial.println(value, BIN);  // Print in binary
    Serial.print("Decimal: ");
    Serial.println(value);
  }
  
  // Small delay to prevent busy looping
  delay(10);
}