/* Arduino DRO Adaptor
This code reads 21-bit data frames from a DRO scale using a clock and data line generated by the scale.
It uses interrupts to capture the clock signal and read the corresponding data bits, ensuring accurate timing and synchronization.
The received data is stored to be re-emitted to a TouchDRO adaptor using a clock generated by the adaptor itself,
allowing the TouchDRO to receive the data as if it were directly connected to a scale that requires an external clock.

*/
#include <Arduino.h>

// Pin definitions
#define INPUT_CLOCK_PIN 1  // D1 This is the input for the clock signal generated by the DRO scale.
#define INPUT_DATA_PIN 2   // D2 This is the input for the data signal generated by the DRO scale.
#define OUTPUT_CLOCK_PIN 3 // D3 This is the input for the clock signal generated by the TouchDRO adaptor.
#define OUTPUT_DATA_PIN 4  // D4 This is the output for the data signal that will be sent to the TouchDRO adaptor.

#define MAX_BITS 21
#define MIN_FRAME_SPACING 3000 // Much larger than bit spacing but smaller than expected frame spacing, in microseconds.

// Volatile variables for interrupt handling
volatile uint32_t receivedData = 0; // safe variable to share outside of the ISR. holds the most recently received 21-bit data frame.
volatile bool dataReady = false; // Flag to indicate that a complete data frame has been received and is ready to be read outside of the ISR.

// Interrupt service routine for the inputclock signal
void onInputClock()
{

  // Set up static variables for this ISR
  static uint32_t currentTime = 0;
  static uint32_t lastClockTime = 0;
  static uint32_t clockInterval = 0;
  static int bitCount = 0;
  
  // Get the current time in microseconds
  if (lastClockTime == 0)
  {
    lastClockTime = micros(); // This is the first pulse seen so prime the pulse timer and return to avoid triggering a frame on the first pulse seen.
    return;                   
  }

  currentTime = micros();

  if (dataReady)
  {
    return; // Ignore additional clock pulses if data is already ready and not read yet.
  }

  // Calculate the interval since the last clock pulse
  clockInterval = currentTime - lastClockTime;
  lastClockTime = currentTime; // Update last clock time

  if (bitCount == 0) // Check for the first clock pulse when we are expecting the start of a new data frame
  {
    if (clockInterval < MIN_FRAME_SPACING)
    {
      return; // Not a valid first clock pulse, ignore and wait for the next one
    };
  }
  else 
  {
    if (clockInterval > MIN_FRAME_SPACING) // Test to make sure this is a data bit.
    {
      // Bit clock interval too long, this frame is out of sync, reset state to wait for the next start of frame
      bitCount = 0;
      receivedData = 0;
      return;
    }
  }

  // If we got this far we have a data bit and are in a data frame.
  // Read the data bit
  int bit = digitalRead(INPUT_DATA_PIN);

  // Shift in the bit
  if (bit)
  {
    receivedData |= ((long)0x00100000); // Set the 21st bit if the bit is 1
  }
  receivedData >>= 1;

  // Increment bit count
  bitCount++;

  // Check if we have received all 21 bits
  if (bitCount >= 21)
  {
    dataReady = true;
    bitCount = 0;    // Reset bit count for the next data frame
  }
}

void setup()
{
  // Initialize serial for output
  Serial.begin(115200);
  while (!Serial)
    ;
  Serial.println("DRO Adaptor starting.");
  // Set pin modes
  pinMode(INPUT_CLOCK_PIN, INPUT);
  pinMode(INPUT_DATA_PIN, INPUT);

  // Attach interrupt to clock pin (falling edge)
  attachInterrupt(digitalPinToInterrupt(INPUT_CLOCK_PIN), onInputClock, FALLING);

  Serial.println("DRO Adaptor initialized. Waiting for data...");
}

void loop()
{
  // Check if data is ready
  if (dataReady)
  {

    uint32_t bufferedData = 0;
    // Disable interrupts temporarily to safely read volatile variables
    noInterrupts();
    bufferedData = receivedData;
    dataReady = false;
    receivedData = 0;
    interrupts();

    // Output the value
    // Serial.println(millis());
    // Serial.print("Received 21-bit value: ");
    Serial.println(bufferedData, BIN); // Print in binary
                                       // Serial.print("Clock Interval: ");
    //  for (int i = 0; i < 21; i++){
    //       Serial.print(cachedFrameTimes[i]);
    //       Serial.print(" ");
    //     }
    // Serial.println("");

  }

  // Small delay to prevent busy looping
  // delay(10);
}